---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

# The valkey-tools package is only offered in the backports package
# repository on Debian Bookworm.
- name: Setup backports
  ansible.builtin.include_role:
    name: backports
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release in ["bookworm"]

- name: Install valkey-cli
  ansible.builtin.package:
    name: "{{ package_names }}"
